### PR TITLE
Fixed issue #11: Resizing of text

### PR DESCRIPTION
**Pull request by diruuu**
Add a few lines to detect if the element is text so it can change the font-size instead of the width & height of the element on resize event.

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Thans for your contribution. Looks like everyone like to reformat my code^^.
Any reason why you used `return false` instead of just `break`?

**Comment by diruuu** [comment]
Ah, you're right. Better to use `break` then. I just barely use `switch` and little bit forget about that magic word.

My Sublime Text automatically beautify the JS. Didn't know it will reformat your code. Sorry man.

**Comment by Fuzzyma** [comment]
jup - often happens bacause I just use plain old notepad++ :D
The only reason this bothers me is the fact that this not really belongs to the fix and nobdoy cant track your changes between all this changed stuff. In some cases it donest even look better ^^

However: Please replace the return with the break and run grunt. I then will merge it

**Comment by diruuu** [comment]
I didn't get any luck with the `break`. Apparently the `break` only works at the end of the `case`, so I keep using `return false`. Correct me if I'm wrong.

Btw, I did run grunt.

**Comment by Fuzzyma** [comment]
Oh - of course. Stupid me! Yes you have to use return because its inside a function :D.
However there is no point in returning false. A simple return will to the job, too.
Could you please change that? :)

**Comment by diruuu** [comment]
Of course, man. Done.

**Pull request merged**
