### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by albohlabs**
Update the readme events and add known issues section.

### CODE REVIEW

**Comment by Fuzzyma** [comment]
What do you mean with `nested elements`?

**Comment by albohlabs** [comment]
I'm referring your [comment](https://github.com/Fuzzyma/svg.resize.js/issues/4#issuecomment-111014608) in #4. Should i rename `elements` to `svgs` to make it more clear?

**Comment by Fuzzyma** [comment]
Yes - that would be better. `nested svgs` is the correct term imo :)

**Comment by albohlabs** [comment]
done.

**Comment by Fuzzyma** [comment]
thank you!

**Pull request merged**
