### PR TITLE
Added resizestart event

### PR DESCRIPTION
**Pull request by GuskiS**
I have added `resizestart` event, but how do I add it to `dist` correctly? Never done it before.

### CODE REVIEW

**Comment by Fuzzyma** [comment]
You may want to pass valuable parameters to the event as seen with the `resizing` event:
```javascript
this.el.fire('resizing', {dx: diffX, dy: diffY, event: event});
```

As for the dist: Run `npm install` and then run `grunt`

**Comment by GuskiS** [comment]
Changed and runned grunt, thanks :)

**Comment by Fuzzyma** [comment]
thanks!

**Comment by GuskiS** [comment]
Sweet, when is this gonna be on NPM?

**Comment by Fuzzyma** [comment]
Published just now as `1.4.0`

**Pull request merged**
