### PR TITLE
[New Feature]: Added resizeLimits parameter

### PR DESCRIPTION
**Pull request by galdeguer-ut**
## Changelog
* Added new parameter `resizeLimits`. On resize, it will check if the new rect has the minimum size defined with this parameter. (default `{  width: 0, height: 0 }`) Related #33

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Hey sorry for coming back to you this late. Was doing diploma. So does this work in all possiby scenarios like transformed element, transformed parent and so on?

**Comment by galdeguer** [comment]
> Hey sorry for coming back to you this late. Was doing diploma. So does this work in all possiby scenarios like transformed element, transformed parent and so on?

I didn't test this case. I'll test it. Thank you!

**Comment by galdeguer** [comment]
@Fuzzyma hey, I tested theses cases:
* Transformed element
* Transformed parent

It seems it's working well.

**Comment by Fuzzyma** [comment]
Does it work when you resize in negative direction?

**Comment by galdeguer** [comment]
@Fuzzyma mmmm, what do you mean with "negative direction"?

I'll send you a codesandbox to show you the behaviour:

https://codesandbox.io/embed/svgjs-tyhmk?fontsize=14&hidenavigation=1&theme=dark

**Comment by Fuzzyma** [comment]
Oh lol, it is a minimum size. I forgot about that. In that case resizing in the negative direction makes no sense anyway. Nice work!

**Review by Fuzzyma — CHANGES_REQUESTED** [review]
The code looks good to me. However, I noticed, that you supplied default values of {1,1}. This will keep user from resizing into the negative direction (e.g. take bottom right handler and pull it over the top left - it should work nevertheless and treat your handler as the top left edge now).
So it either has to be possible to do that WITH your option enabled or there has to be a way to disable this option alltogether

**Comment by galdeguer** [comment]
@Fuzzyma I fixed the default values to {0, 0}, to follow the same code as before my change. Following the example that you say, I can't resize in negative direction in your examples right now (https://svgjs.com/svg.resize.js/demo/index.html) Maybe there is something broken in production?

**Comment by Fuzzyma** [comment]
Right, my fault. Thats only for drawing and not for resizing. Slightly confused :D.
In that case, it's all correct. Default of 0,0 is fine, too. Will merge when I get back on my pc

**Pull request merged**
